package com.careful.HyperFVM.utils.ForCardData;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;

public class DisplayBackgroundCardImageHelper {
    private static final String[][] CardImageFileNameArray = {
            {"card_data_index_1_1_1_2_big", "双向水管", "card_data_1"},
            {"card_data_index_1_1_2_2_big", "天秤座精灵", "card_data_4"},
            {"card_data_index_1_1_3_2_big", "呆呆鸡", "card_data_4"},
            {"card_data_index_1_1_4_2_big", "阿瑞斯神使", "card_data_3"},
            {"card_data_index_1_1_4_3_big", "阿瑞斯神使", "card_data_3"},
            {"card_data_index_1_1_5_2_big", "二哈汪", "card_data_4"},
            {"card_data_index_1_1_6_2_big", "双枪喵", "card_data_4"},
            {"card_data_index_1_1_7_2_big", "散弹牛", "card_data_4"},
            {"card_data_index_1_1_8_2_big", "威风虎", "card_data_4"},

            {"card_data_index_1_2_1_2_big", "三线酒架", "card_data_1"},
            {"card_data_index_1_2_2_2_big", "射手座精灵", "card_data_4"},
            {"card_data_index_1_2_3_2_big", "砰砰鸡", "card_data_4"},
            {"card_data_index_1_2_4_2_big", "丘比特神使", "card_data_3"},
            {"card_data_index_1_2_4_3_big", "丘比特神使", "card_data_3"},
            {"card_data_index_1_2_5_2_big", "狩猎汪", "card_data_4"},
            {"card_data_index_1_2_6_2_big", "猪猪猎手", "card_data_4"},

            {"card_data_index_1_3_1_2_big", "枪塔喵", "card_data_4"},
            {"card_data_index_1_3_2_2_big", "弩箭牛", "card_data_4"},
            {"card_data_index_1_3_3_2_big", "仙人掌刺身", "card_data_1"},

            {"card_data_index_2_1_1_2_big", "勺勺兔", "card_data_4"},
            {"card_data_index_2_1_2_2_big", "窃蛋龙", "card_data_4"},
            {"card_data_index_2_1_3_2_big", "尤弥尔神使", "card_data_3"},
            {"card_data_index_2_1_3_3_big", "尤弥尔神使", "card_data_3"},
            {"card_data_index_2_1_4_2_big", "幻影蛇", "card_data_4"},
            {"card_data_index_2_1_5_2_big", "全能糖球投手", "card_data_1"},
            {"card_data_index_2_1_6_2_big", "金乌马", "card_data_4"},

            {"card_data_index_2_2_1_2_big", "煮蛋器投手", "card_data_1"},
            {"card_data_index_2_2_2_2_big", "冰煮蛋器", "card_data_1"},
            {"card_data_index_2_2_3_2_big", "双鱼座精灵", "card_data_4"},
            {"card_data_index_2_2_4_2_big", "弹弹鸡", "card_data_4"},
            {"card_data_index_2_2_5_2_big", "索尔神使", "card_data_3"},
            {"card_data_index_2_2_5_3_big", "索尔神使", "card_data_3"},
            {"card_data_index_2_2_6_2_big", "机械汪", "card_data_4"},
            {"card_data_index_2_2_7_2_big", "投弹猪", "card_data_4"},
            {"card_data_index_2_2_8_2_big", "雪糕投手", "card_data_1"},
            {"card_data_index_2_2_9_2_big", "飞鱼喵", "card_data_4"},
            {"card_data_index_2_2_10_2_big", "壮壮牛", "card_data_4"},
            {"card_data_index_2_2_11_2_big", "烤蜥蜴投手", "card_data_1"},
            {"card_data_index_2_2_12_2_big", "投篮虎", "card_data_4"},
            {"card_data_index_2_2_13_2_big", "钵钵鸡", "card_data_1"},

            {"card_data_index_2_3_1_2_big", "色拉投手", "card_data_1"},
            {"card_data_index_2_3_2_2_big", "巧克力投手", "card_data_1"},
            {"card_data_index_2_3_3_2_big", "臭豆腐投手", "card_data_1"},
            {"card_data_index_2_4_4_2_big", "8周年蛋糕", "card_data_1"},

            {"card_data_index_3_1_1_2_big", "炭烧海星", "card_data_1"},
            {"card_data_index_3_1_2_2_big", "猪猪料理机", "card_data_4"},
            {"card_data_index_3_1_3_2_big", "陀螺喵", "card_data_4"},
            {"card_data_index_3_1_4_2_big", "哈迪斯神使", "card_data_3"},
            {"card_data_index_3_1_4_3_big", "哈迪斯神使", "card_data_3"},
            {"card_data_index_3_1_5_2_big", "查克拉兔", "card_data_4"},

            {"card_data_index_3_2_1_2_big", "厨师虎", "card_data_4"},
            {"card_data_index_3_2_2_2_big", "星星兔", "card_data_4"},
            {"card_data_index_3_2_3_2_big", "坚果爆炒机", "card_data_1"},
            {"card_data_index_3_2_4_2_big", "里格神使", "card_data_3"},
            {"card_data_index_3_2_4_3_big", "里格神使", "card_data_3"},
            {"card_data_index_3_2_5_2_big", "怪味鱿鱼", "card_data_1"},
            {"card_data_index_3_2_6_2_big", "烟花虎", "card_data_4"},
            {"card_data_index_3_2_7_2_big", "风车龙", "card_data_4"},

            {"card_data_index_3_3_1_2_big", "鲈鱼", "card_data_1"},
            {"card_data_index_3_3_2_2_big", "便便汪", "card_data_4"},
            {"card_data_index_3_3_3_2_big", "烧鸡", "card_data_1"},
            {"card_data_index_3_3_4_2_big", "饼干汪", "card_data_4"},
            {"card_data_index_3_3_5_0_big", "牛角面包", "card_data_1"},
            {"card_data_index_3_3_6_1_big", "盾盾汪", "card_data_4"},

            {"card_data_index_4_1_1_2_big", "火盆", "card_data_1"},
            {"card_data_index_4_1_2_2_big", "金牛座精灵", "card_data_4"},
            {"card_data_index_4_1_3_2_big", "洛基神使", "card_data_3"},
            {"card_data_index_4_1_3_3_big", "洛基神使", "card_data_3"},
            {"card_data_index_4_1_4_2_big", "暖炉汪", "card_data_4"},
            {"card_data_index_4_1_5_2_big", "能量喵", "card_data_4"},
            {"card_data_index_4_1_6_2_big", "坩埚蛇", "card_data_4"},
            {"card_data_index_4_1_7_2_big", "猪猪加强器", "card_data_4"},
            {"card_data_index_4_1_8_0_big", "蓝莓信号塔塔", "card_data_1"},
            {"card_data_index_4_1_9_2_big", "美味水果塔", "card_data_1"},
            {"card_data_index_4_1_10_2_big", "欧若拉神使", "card_data_3"},
            {"card_data_index_4_1_10_3_big", "欧若拉神使", "card_data_3"},

            {"card_data_index_4_2_1_2_big", "莓果点心", "card_data_1"},
            {"card_data_index_4_2_2_2_big", "香料虎", "card_data_4"},
            {"card_data_index_4_2_3_2_big", "塔利亚神使", "card_data_3"},
            {"card_data_index_4_2_3_3_big", "塔利亚神使", "card_data_3"},
            {"card_data_index_4_2_4_2_big", "精灵龙", "card_data_4"},
            {"card_data_index_4_2_5_2_big", "龙须面", "card_data_1"},
            {"card_data_index_4_2_6_2_big", "五谷丰登", "card_data_1"},
            {"card_data_index_4_2_7_2_big", "五行蛇", "card_data_4"},
            {"card_data_index_4_2_8_2_big", "弗雷神使", "card_data_3"},
            {"card_data_index_4_2_8_3_big", "弗雷神使", "card_data_3"},
            {"card_data_index_4_2_9_2_big", "加速榨汁机", "card_data_1"},
            {"card_data_index_4_2_10_2_big", "魔杖蛇", "card_data_4"},
            {"card_data_index_4_2_11_2_big", "塔拉萨神使", "card_data_3"},
            {"card_data_index_4_2_11_3_big", "塔拉萨神使", "card_data_3"},
            {"card_data_index_4_2_12_2_big", "音盒马", "card_data_4"},
            {"card_data_index_4_2_13_2_big", "炎焱兔", "card_data_4"},

            {"card_data_index_4_3_1_0_big", "11周年美食盒子", "card_data_1"},
            {"card_data_index_4_3_2_2_big", "战旗马", "card_data_4"},

            {"card_data_index_5_1_1_2_big", "小火炉", "card_data_1"},
            {"card_data_index_5_1_2_2_big", "大火炉", "card_data_1"},
            {"card_data_index_5_1_3_2_big", "酒杯灯", "card_data_1"},
            {"card_data_index_5_1_4_2_big", "双子座精灵", "card_data_4"},
            {"card_data_index_5_1_5_2_big", "咕咕鸡", "card_data_4"},
            {"card_data_index_5_1_6_2_big", "暖暖鸡", "card_data_4"},
            {"card_data_index_5_1_7_2_big", "阿波罗神使", "card_data_3"},
            {"card_data_index_5_1_7_3_big", "阿波罗神使", "card_data_3"},
            {"card_data_index_5_1_8_0_big", "7周年蜡烛", "card_data_1"},
            {"card_data_index_5_1_9_2_big", "火焰牛", "card_data_4"},
            {"card_data_index_5_1_10_2_big", "花火龙", "card_data_4"},
            {"card_data_index_5_1_11_2_big", "蛇羹煲", "card_data_1"},
            {"card_data_index_5_1_12_2_big", "禅心马", "card_data_4"},

            {"card_data_index_5_2_1_2_big", "钱罐猪", "card_data_4"},
            {"card_data_index_5_2_2_2_big", "罐罐牛", "card_data_4"},
            {"card_data_index_5_2_3_2_big", "烈火虎", "card_data_4"},

            {"card_data_index_6_1_1_2_big", "樱桃反弹布丁", "card_data_1"},
            {"card_data_index_6_1_2_0_big", "艾草粑粑", "card_data_1"},
            {"card_data_index_6_1_3_2_big", "布丁汪", "card_data_4"},
            {"card_data_index_6_1_4_2_big", "凉粉牛", "card_data_4"},
            {"card_data_index_6_1_5_2_big", "忒提丝神使", "card_data_3"},
            {"card_data_index_6_1_5_3_big", "忒提丝神使", "card_data_3"},

            {"card_data_index_6_2_1_2_big", "木盘子", "card_data_1"},
            {"card_data_index_6_2_2_2_big", "盘盘鸡", "card_data_4"},
            {"card_data_index_6_2_3_2_big", "猫猫盘", "card_data_4"},
            {"card_data_index_6_2_4_2_big", "魔法软糖", "card_data_1"},
            {"card_data_index_6_2_5_2_big", "棉花糖", "card_data_1"},
            {"card_data_index_6_2_6_1_big", "苏打气泡", "card_data_1"},
            {"card_data_index_6_2_7_1_big", "麦芽糖", "card_data_1"},

            {"card_data_index_7_1_1_2_big", "糖葫芦炮弹", "card_data_1"},
            {"card_data_index_7_1_2_2_big", "跳跳鸡", "card_data_4"},
            {"card_data_index_7_1_3_2_big", "防空喵", "card_data_4"},
            {"card_data_index_7_1_4_2_big", "赫丘利神使", "card_data_3"},
            {"card_data_index_7_1_4_3_big", "赫丘利神使", "card_data_3"},

            {"card_data_index_7_2_1_0_big", "香肠", "card_data_1"},
            {"card_data_index_7_2_2_2_big", "热狗大炮", "card_data_1"},
            {"card_data_index_7_2_3_2_big", "弹簧虎", "card_data_4"},
            {"card_data_index_7_2_4_2_big", "泡泡龙", "card_data_4"},
            {"card_data_index_7_2_5_2_big", "爱心便当", "card_data_1"},
            {"card_data_index_7_2_6_2_big", "梦幻多拿滋", "card_data_1"},
            {"card_data_index_7_2_7_2_big", "埃罗斯神使", "card_data_3"},
            {"card_data_index_7_2_7_3_big", "埃罗斯神使", "card_data_3"},
            {"card_data_index_7_2_8_2_big", "耗油双菇", "card_data_1"},
            {"card_data_index_7_2_9_2_big", "奶茶猪", "card_data_4"},
            {"card_data_index_7_2_10_2_big", "科技喵", "card_data_4"},

            {"card_data_index_8_1_1_2_big", "咖啡喷壶", "card_data_1"},
            {"card_data_index_8_1_2_2_big", "关东煮喷锅", "card_data_1"},
            {"card_data_index_8_1_3_2_big", "烈焰龙", "card_data_4"},
            {"card_data_index_8_1_4_2_big", "赫斯提亚神使", "card_data_3"},
            {"card_data_index_8_1_4_3_big", "赫斯提亚神使", "card_data_3"},

            {"card_data_index_8_2_1_2_big", "旋转咖啡喷壶", "card_data_1"},
            {"card_data_index_8_2_2_2_big", "狮子座精灵", "card_data_4"},
            {"card_data_index_8_2_3_2_big", "波塞冬神使", "card_data_3"},
            {"card_data_index_8_2_3_3_big", "波塞冬神使", "card_data_3"},
            {"card_data_index_8_2_4_2_big", "转转鸡", "card_data_4"},
            {"card_data_index_8_2_5_2_big", "可乐汪", "card_data_4"},
            {"card_data_index_8_2_6_2_big", "元气牛", "card_data_4"},
            {"card_data_index_8_2_7_2_big", "巫蛊蛇", "card_data_4"},

            {"card_data_index_9_1_1_2_big", "章鱼烧", "card_data_1"},
            {"card_data_index_9_1_2_2_big", "巨蟹座精灵", "card_data_4"},
            {"card_data_index_9_1_3_2_big", "忍忍鸡", "card_data_4"},
            {"card_data_index_9_1_4_2_big", "狄安娜神使", "card_data_3"},
            {"card_data_index_9_1_4_3_big", "狄安娜神使", "card_data_3"},
            {"card_data_index_9_1_5_2_big", "飞盘汪", "card_data_4"},
            {"card_data_index_9_1_6_2_big", "铁甲飞镖猪", "card_data_4"},
            {"card_data_index_9_1_7_2_big", "海盗兔", "card_data_4"},

            {"card_data_index_9_2_1_2_big", "咖喱龙虾炮", "card_data_1"},
            {"card_data_index_9_2_2_2_big", "雅典娜守护", "card_data_4"},
            {"card_data_index_9_2_3_2_big", "火箭猪", "card_data_4"},
            {"card_data_index_9_2_4_2_big", "宙斯神使", "card_data_3"},
            {"card_data_index_9_2_4_3_big", "宙斯神使", "card_data_3"},

            {"card_data_index_9_3_1_2_big", "魔法猪", "card_data_4"},
            {"card_data_index_9_3_2_2_big", "招财喵", "card_data_4"},
            {"card_data_index_9_3_3_2_big", "雪球兔", "card_data_4"},
            {"card_data_index_9_3_4_2_big", "典伊神使", "card_data_3"},
            {"card_data_index_9_3_4_3_big", "典伊神使", "card_data_3"},
            {"card_data_index_9_3_5_2_big", "冰晶龙", "card_data_4"},
            {"card_data_index_9_3_6_2_big", "冰块冷萃机", "card_data_1"},

            {"card_data_index_9_4_1_1_big", "鼠鼠蛋糕空投器", "card_data_1"},
            {"card_data_index_9_4_2_2_big", "风力空投猪", "card_data_4"},
            {"card_data_index_9_4_3_2_big", "电流虎", "card_data_4"},
            {"card_data_index_9_4_4_2_big", "霹雳马", "card_data_4"},
            {"card_data_index_9_4_5_2_big", "金刚马", "card_data_4"},
            {"card_data_index_9_4_6_2_big", "归元马", "card_data_4"},
            {"card_data_index_9_4_7_2_big", "蜜糖陷阱", "card_data_1"},
            {"card_data_index_9_4_8_2_big", "萌海马", "card_data_4"},

            {"card_data_index_10_1_1_2_big", "肥牛火锅", "card_data_1"},
            {"card_data_index_10_1_2_2_big", "麻辣香锅", "card_data_1"},
            {"card_data_index_10_1_3_2_big", "生煎锅", "card_data_1"},
            {"card_data_index_10_1_4_2_big", "铛铛虎", "card_data_4"},
            {"card_data_index_10_1_5_2_big", "祝融神使", "card_data_3"},
            {"card_data_index_10_1_5_3_big", "祝融神使", "card_data_3"},
            {"card_data_index_10_1_6_2_big", "糖炒栗子", "card_data_1"},
            {"card_data_index_10_1_7_2_big", "霜霜蛇", "card_data_4"},
            {"card_data_index_10_1_8_2_big", "马卡龙烤箱", "card_data_1"},

            {"card_data_index_10_2_1_2_big", "汉堡包", "card_data_1"},
            {"card_data_index_10_2_2_0_big", "贪食娃", "card_data_1"},
            {"card_data_index_10_2_3_2_big", "吞噬龙", "card_data_4"},
            {"card_data_index_10_2_4_2_big", "香辣年糕蟹", "card_data_1"},
            {"card_data_index_10_2_5_2_big", "混沌神使", "card_data_3"},

            {"card_data_index_10_3_1_2_big", "新疆炒面", "card_data_1"},
            {"card_data_index_10_3_2_2_big", "丸子厨师", "card_data_1"},
            {"card_data_index_10_3_3_2_big", "功夫汪", "card_data_4"},
            {"card_data_index_10_3_4_2_big", "拳皇马", "card_data_4"},
            {"card_data_index_10_3_5_0_big", "鱼刺", "card_data_1"},
            {"card_data_index_10_3_6_2_big", "钢鱼刺", "card_data_1"},
            {"card_data_index_10_3_7_2_big", "糖渍刺梨", "card_data_1"},

            {"card_data_index_10_4_1_2_big", "蜂蜜史莱姆", "card_data_1"},
            {"card_data_index_10_4_2_2_big", "糖人马", "card_data_4"},

            {"card_data_index_11_1_1_0_big", "小笼包", "card_data_1"},
            {"card_data_index_11_1_2_0_big", "双层小笼包", "card_data_1"},
            {"card_data_index_11_1_3_0_big", "三向小笼包", "card_data_1"},
            {"card_data_index_11_1_4_2_big", "机枪小笼包", "card_data_1"},
            {"card_data_index_11_1_5_0_big", "冰冻小笼包", "card_data_1"},
            {"card_data_index_11_1_6_0_big", "双层冰冻小笼包", "card_data_1"},
            {"card_data_index_11_1_7_0_big", "三向冰冻小笼包", "card_data_1"},
            {"card_data_index_11_1_8_0_big", "机枪冰冻小笼包", "card_data_1"},
            {"card_data_index_11_1_9_2_big", "国王小笼包", "card_data_1"},
            {"card_data_index_11_1_10_2_big", "三向国王小笼包", "card_data_1"},
            {"card_data_index_11_1_11_0_big", "贵族小笼包", "card_data_1"},
            {"card_data_index_11_1_12_2_big", "玉蜀黍", "card_data_1"},
            {"card_data_index_11_1_13_2_big", "包包龙", "card_data_4"},
            {"card_data_index_11_1_14_2_big", "咖啡杯", "card_data_1"},
            {"card_data_index_11_1_15_0_big", "水上茶杯", "card_data_1"},
            {"card_data_index_11_1_16_2_big", "激光汪", "card_data_4"},

            {"card_data_index_11_2_1_2_big", "阴阳蛇", "card_data_4"},
            {"card_data_index_11_2_2_2_big", "焚寂马", "card_data_4"},
            {"card_data_index_11_2_3_2_big", "弹珠汽水", "card_data_1"},

            {"card_data_index_11_3_1_1_big", "天蝎座精灵", "card_data_4"},
            {"card_data_index_11_3_2_2_big", "工程猪", "card_data_4"},
            {"card_data_index_11_3_3_2_big", "双刃蛇", "card_data_4"},
            {"card_data_index_11_3_4_2_big", "元素蛇", "card_data_4"},
            {"card_data_index_11_3_5_2_big", "御风马", "card_data_4"},
            {"card_data_index_11_3_6_2_big", "回旋虎", "card_data_4"},
            {"card_data_index_11_3_7_2_big", "大师兔", "card_data_4"},
            {"card_data_index_11_3_8_2_big", "15周年猴赛雷", "card_data_1"},
            {"card_data_index_11_3_9_2_big", "赖皮蛇", "card_data_4"},
            {"card_data_index_11_3_10_2_big", "迷你披萨炉", "card_data_1"},
            {"card_data_index_11_3_11_2_big", "鲁班神使", "card_data_3"},
            {"card_data_index_11_3_11_3_big", "鲁班神使", "card_data_3"},
            {"card_data_index_11_3_12_2_big", "炎凰马", "card_data_4"},

            {"card_data_index_11_4_1_2_big", "焦油喷壶", "card_data_1"},
            {"card_data_index_11_4_2_2_big", "喷壶汪", "card_data_4"},
            {"card_data_index_11_4_3_2_big", "派派鸡", "card_data_4"},
            {"card_data_index_11_4_4_2_big", "小猪米花机", "card_data_4"},
            {"card_data_index_11_4_5_2_big", "喷气牛", "card_data_4"},
            {"card_data_index_11_4_6_2_big", "卖萌喵", "card_data_4"},
            {"card_data_index_11_4_7_2_big", "奥丁神使", "card_data_3"},
            {"card_data_index_11_4_7_3_big", "奥丁神使", "card_data_3"},
            {"card_data_index_11_4_8_2_big", "法师蛇", "card_data_4"},
            {"card_data_index_11_4_9_2_big", "街头烤肉大师", "card_data_1"},
            {"card_data_index_11_4_10_2_big", "后羿神使", "card_data_3"},
            {"card_data_index_11_4_10_3_big", "后羿神使", "card_data_3"},

            {"card_data_index_12_1_1_2_big", "雷电长棍面包", "card_data_1"},
            {"card_data_index_12_1_2_2_big", "三指兔", "card_data_4"},
            {"card_data_index_12_1_3_2_big", "结界马", "card_data_4"},
            {"card_data_index_12_1_4_2_big", "巧克力大炮", "card_data_1"},
            {"card_data_index_12_1_5_2_big", "导弹蛇", "card_data_4"},
            {"card_data_index_12_1_6_2_big", "盖亚神使", "card_data_3"},
            {"card_data_index_12_1_6_3_big", "盖亚神使", "card_data_3"},

            {"card_data_index_12_2_1_2_big", "可乐炸弹", "card_data_1"},
            {"card_data_index_12_2_2_2_big", "酒瓶炸弹", "card_data_1"},
            {"card_data_index_12_2_3_2_big", "开水壶炸弹", "card_data_1"},
            {"card_data_index_12_2_4_2_big", "威士忌炸弹", "card_data_1"},
            {"card_data_index_12_2_5_2_big", "潘多拉", "card_data_3"},
            {"card_data_index_12_2_5_3_big", "潘多拉", "card_data_3"},
            {"card_data_index_12_2_6_0_big", "深水炸弹", "card_data_1"},
            {"card_data_index_12_2_7_2_big", "爆辣河豚", "card_data_1"},
            {"card_data_index_12_2_8_0_big", "爆竹", "card_data_1"},
            {"card_data_index_12_2_9_0_big", "美食烟花普通版", "card_data_1"},
            {"card_data_index_12_2_10_0_big", "美食烟花华丽版", "card_data_1"},
            {"card_data_index_12_2_11_2_big", "水瓶座精灵", "card_data_4"},
            {"card_data_index_12_2_12_2_big", "雷暴猪", "card_data_4"},
            {"card_data_index_12_2_13_2_big", "微波炉爆弹", "card_data_1"},
            {"card_data_index_12_2_14_2_big", "玉兔灯笼", "card_data_1"},
            {"card_data_index_12_2_15_2_big", "爆裂蛇", "card_data_4"},
            {"card_data_index_12_2_16_2_big", "糖果罐子", "card_data_1"},
            {"card_data_index_12_2_17_2_big", "烛阴龙", "card_data_4"},
            {"card_data_index_12_2_18_2_big", "老鼠夹子", "card_data_1"},
            {"card_data_index_12_2_19_0_big", "麻辣串炸弹", "card_data_1"},
            {"card_data_index_12_2_20_0_big", "竹筒粽子", "card_data_1"},
            {"card_data_index_12_2_21_2_big", "娇娇虎", "card_data_4"},
            {"card_data_index_12_2_22_2_big", "泡泡鸡尾酒", "card_data_1"},

            {"card_data_index_12_3_1_2_big", "辣椒粉", "card_data_1"},
            {"card_data_index_12_3_2_0_big", "月蟾兔", "card_data_1"},
            {"card_data_index_12_3_3_2_big", "爆炸汪", "card_data_4"},
            {"card_data_index_12_3_5_2_big", "10周年烟花", "card_data_1"},
            {"card_data_index_12_3_6_2_big", "芥末牛", "card_data_4"},

            {"card_data_index_13_1_1_0_big", "钢丝球", "card_data_1"},
            {"card_data_index_13_1_2_0_big", "炸地鼠爆竹", "card_data_1"},
            {"card_data_index_13_1_3_2_big", "面粉袋", "card_data_1"},
            {"card_data_index_13_1_4_2_big", "椰子果", "card_data_1"},
            {"card_data_index_13_1_5_2_big", "青涩柿柿", "card_data_1"},
            {"card_data_index_13_1_6_0_big", "萌虎高压锅", "card_data_1"},
            {"card_data_index_13_1_7_0_big", "白羊座精灵", "card_data_4"},
            {"card_data_index_13_1_8_2_big", "酋长汪", "card_data_4"},
            {"card_data_index_13_1_9_2_big", "逗猫棒", "card_data_4"},
            {"card_data_index_13_1_10_2_big", "金牛烟花", "card_data_1"},
            {"card_data_index_13_1_11_2_big", "贪吃兔", "card_data_4"},
            {"card_data_index_13_1_12_2_big", "灵鱼摩蹉神使", "card_data_3"},
            {"card_data_index_13_1_12_3_big", "灵鱼摩蹉神使", "card_data_3"},

            {"card_data_index_13_2_1_2_big", "榴莲", "card_data_1"},
            {"card_data_index_13_2_2_2_big", "美味电鳗", "card_data_1"},
            {"card_data_index_13_2_3_2_big", "镭射喵", "card_data_4"},
            {"card_data_index_13_2_4_2_big", "黑暗神使", "card_data_3"},
            {"card_data_index_13_2_4_3_big", "黑暗神使", "card_data_3"},
            {"card_data_index_13_2_5_0_big", "火龙果", "card_data_1"},
            {"card_data_index_13_2_6_0_big", "摩羯座精灵", "card_data_4"},
            {"card_data_index_13_2_7_2_big", "龙珠果", "card_data_4"},
            {"card_data_index_13_2_8_2_big", "巴德尔神使", "card_data_3"},
            {"card_data_index_13_2_8_3_big", "巴德尔神使", "card_data_3"},

            {"card_data_index_13_3_1_2_big", "冰桶炸弹", "card_data_1"},
            {"card_data_index_13_3_2_2_big", "冰弹喵", "card_data_4"},
            {"card_data_index_13_3_3_2_big", "冰兔菓子", "card_data_1"},
            {"card_data_index_13_3_4_2_big", "泡泡糖", "card_data_1"},
            {"card_data_index_13_3_5_2_big", "逆转牛", "card_data_4"},

            {"card_data_index_13_4_1_2_big", "蛋蛋兔", "card_data_4"},

            {"card_data_index_14_1_1_2_big", "冰激凌", "card_data_1"},
            {"card_data_index_14_1_2_2_big", "转龙壶", "card_data_4"},
            {"card_data_index_14_1_3_2_big", "美味计时器", "card_data_1"},
            {"card_data_index_14_1_4_2_big", "柯罗诺斯神使", "card_data_3"},
            {"card_data_index_14_1_4_3_big", "柯罗诺斯神使", "card_data_3"},
            {"card_data_index_14_1_5_2_big", "幻幻鸡", "card_data_4"},
            {"card_data_index_14_1_6_2_big", "百变蛇", "card_data_4"},
            {"card_data_index_14_1_7_2_big", "梵天神使", "card_data_3"},
            {"card_data_index_14_1_7_3_big", "梵天神使", "card_data_3"},
            {"card_data_index_14_1_8_2_big", "顽皮龙", "card_data_4"},
            {"card_data_index_14_1_9_2_big", "圣诞包裹", "card_data_1"},
            {"card_data_index_14_1_10_2_big", "天使猪", "card_data_4"},
            {"card_data_index_14_1_11_2_big", "黯然销魂饭", "card_data_1"},
            {"card_data_index_14_1_12_2_big", "星穹马", "card_data_4"},
            {"card_data_index_14_1_13_2_big", "奥西里斯神使", "card_data_3"},
            {"card_data_index_14_1_14_2_big", "13周年时光机", "card_data_1"},
            {"card_data_index_14_1_15_2_big", "蛇蛇酒", "card_data_4"},
            {"card_data_index_14_1_16_2_big", "克洛托神使", "card_data_3"},
            {"card_data_index_14_1_16_3_big", "克洛托神使", "card_data_3"},

            {"card_data_index_14_2_1_1_big", "油灯", "card_data_1"},
            {"card_data_index_14_2_2_0_big", "南瓜灯", "card_data_1"},
            {"card_data_index_14_2_3_0_big", "肉松清明粿", "card_data_1"},
            {"card_data_index_14_2_4_2_big", "防萤草灯笼", "card_data_1"},
            {"card_data_index_14_2_5_2_big", "萤火蛇", "card_data_4"},
            {"card_data_index_14_2_6_0_big", "换气扇", "card_data_1"},
            {"card_data_index_14_2_7_2_big", "9周年幸运草扇", "card_data_1"},
            {"card_data_index_14_2_8_1_big", "棕榈吹风机", "card_data_1"},
            {"card_data_index_14_2_9_2_big", "爆爆鸡", "card_data_4"},
            {"card_data_index_14_2_10_2_big", "清障猪", "card_data_4"},
            {"card_data_index_14_2_11_2_big", "旋风牛", "card_data_4"},
            {"card_data_index_14_2_12_2_big", "酸柠檬爆弹", "card_data_1"},
            {"card_data_index_14_2_13_2_big", "炸炸菇", "card_data_1"},
            {"card_data_index_14_2_14_2_big", "海盐粉", "card_data_1"},
            {"card_data_index_14_2_15_2_big", "碎冰喵", "card_data_4"},

            {"card_data_index_14_3_1_1_big", "防风草沙拉", "card_data_1"},
            {"card_data_index_14_3_2_1_big", "金箔甜筒", "card_data_1"},
            {"card_data_index_14_3_3_2_big", "治愈喵", "card_data_4"},
            {"card_data_index_14_3_4_2_big", "12周年能量饮料", "card_data_1"},
            {"card_data_index_14_3_5_0_big", "木塞子", "card_data_1"},
            {"card_data_index_14_3_6_2_big", "咖啡粉", "card_data_1"},
            {"card_data_index_14_3_7_2_big", "尖叫马咖", "card_data_1"},
            {"card_data_index_14_3_8_2_big", "傀儡马", "card_data_4"},

            {"card_data_index_14_4_1_0_big", "猫猫盒", "card_data_1"},
            {"card_data_index_14_4_2_0_big", "猫猫箱", "card_data_1"},
            {"card_data_index_14_4_3_0_big", "小丑盒子", "card_data_1"},
            {"card_data_index_14_4_4_2_big", "鼠乐宝味觉糖", "card_data_1"},
            {"card_data_index_14_4_5_2_big", "大福虎", "card_data_4"},

            {"card_data_index_15_1_1_0_big", "土司面包", "card_data_1"},
            {"card_data_index_15_1_2_0_big", "月饼", "card_data_1"},
            {"card_data_index_15_1_3_0_big", "冰皮月饼", "card_data_1"},
            {"card_data_index_15_1_4_1_big", "巧克力面包", "card_data_1"},
            {"card_data_index_15_1_5_2_big", "菠萝爆炸面包", "card_data_1"},
            {"card_data_index_15_1_6_1_big", "老虎蟹面包", "card_data_1"},
            {"card_data_index_15_1_7_2_big", "桂花酒", "card_data_1"},
            {"card_data_index_15_1_8_0_big", "榴莲千层饼", "card_data_1"},

            {"card_data_index_15_2_1_2_big", "瓜皮护罩", "card_data_4"},
            {"card_data_index_15_2_2_2_big", "处女座精灵", "card_data_4"},
            {"card_data_index_15_2_3_2_big", "赫拉神使", "card_data_3"},
            {"card_data_index_15_2_3_3_big", "赫拉神使", "card_data_3"},
            {"card_data_index_15_2_4_2_big", "祥龙环", "card_data_4"},
            {"card_data_index_15_2_5_2_big", "守能汪", "card_data_4"},
            {"card_data_index_15_2_6_2_big", "生日帽", "card_data_1"},
            {"card_data_index_15_2_7_2_big", "喵喵炉", "card_data_4"},
            {"card_data_index_15_2_8_2_big", "扑克牌护罩", "card_data_1"},
            {"card_data_index_15_2_9_2_big", "彩虹蛇", "card_data_4"},

            {"card_data_index_16_1_1_3_big", "火炉菠萝面包", "card_data_2"},
            {"card_data_index_16_1_2_3_big", "雪芭煮蛋器", "card_data_2"},
            {"card_data_index_16_1_3_3_big", "火影怪味鱿鱼", "card_data_2"},
            {"card_data_index_16_1_4_3_big", "酱香锅烤栗子", "card_data_2"},
            {"card_data_index_16_1_5_3_big", "热狗耗油双菇", "card_data_2"},
            {"card_data_index_16_1_6_3_big", "子母三线酒架", "card_data_2"},
            {"card_data_index_16_1_7_3_big", "刺梨烧烤盘", "card_data_2"},
            {"card_data_index_16_1_8_3_big", "机枪咖啡杯", "card_data_2"},
            {"card_data_index_16_1_9_3_big", "葡萄味软糖", "card_data_2"},
            {"card_data_index_16_1_10_3_big", "脆心死神大炮", "card_data_2"},
    };

    /**
     * 随机选取若干个防御卡大图信息
     * @param fileNum 需要的图片数量
     * @return 选取的图片信息数组
     */
    public static String[][] giveRandomCardImageFileInfoArray(int fileNum) {
        Random random = new Random();
        int totalNum = CardImageFileNameArray.length;

        // 使用Set保证选取的图片是不重复的
        Set<Integer> pickedIndexes = new HashSet<>();
        while (pickedIndexes.size() < fileNum) {
            int index = random.nextInt(totalNum);
            pickedIndexes.add(index);
        }

        // 转换成索引数组
        Integer[] selectedIndexes = pickedIndexes.toArray(new Integer[0]);

        // 通过索引取得对应的文件名
        String[][] cardImageFileNameArray = new String[fileNum][3];
        for (int i = 0; i < fileNum; i++) {
            cardImageFileNameArray[i] = CardImageFileNameArray[selectedIndexes[i]];
        }

        return cardImageFileNameArray;
    }
}
